name: Docker image build

on:
  push:

jobs:
  build:
    name: Build latest Image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64, 386]

    steps:
    - uses: actions/checkout@v2

    - name: Prepare multiarch
      run: sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes
          
    - name: Build latest image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: w_scan_cpp
        archs: ${{ matrix.arch }}
        tags: 20210331-${{ matrix.arch }}
        dockerfiles: |
          ./Dockerfile
        build-args: |
          VERSION=20210331

    - name: Push latest image to ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ghcr.io/${{ github.repository_owner }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
  
  create-manifest:
    needs: build
    name: Create manifest for image
    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: pull latest images
      run: |
        docker pull ghcr.io/${{ github.repository_owner }}/w_scan_cpp:20210331-arm64 
        docker pull ghcr.io/${{ github.repository_owner }}/w_scan_cpp:20210331-amd64
        docker pull ghcr.io/${{ github.repository_owner }}/w_scan_cpp:20210331-386

    - name: create version manifest list
      run: |
        docker manifest create ghcr.io/${{ github.repository_owner }}/w_scan_cpp:20210331 ghcr.io/${{ github.repository_owner }}/w_scan_cpp:20210331-arm64 ghcr.io/${{ github.repository_owner }}/w_scan_cpp:20210331-amd64 ghcr.io/${{ github.repository_owner }}/w_scan_cpp:20210331-386
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:20210331 ghcr.io/${{ github.repository_owner }}/w_scan_cpp:20210331-arm64 --arch arm64
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:20210331 ghcr.io/${{ github.repository_owner }}/w_scan_cpp:20210331-amd64 --arch amd64
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:20210331 ghcr.io/${{ github.repository_owner }}/w_scan_cpp:20210331-386 --arch 386

    - name: push version manifest
      run: |
        docker manifest push ghcr.io/${{ github.repository_owner }}/w_scan_cpp:20210331

    - name: create lates manifest list
      run: |
        docker manifest create ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest ghcr.io/${{ github.repository_owner }}/w_scan_cpp:20210331-arm64 ghcr.io/${{ github.repository_owner }}/w_scan_cpp:20210331-amd64 ghcr.io/${{ github.repository_owner }}/w_scan_cpp:20210331-386
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest ghcr.io/${{ github.repository_owner }}/w_scan_cpp:20210331-arm64 --arch arm64
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest ghcr.io/${{ github.repository_owner }}/w_scan_cpp:20210331-amd64 --arch amd64
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest ghcr.io/${{ github.repository_owner }}/w_scan_cpp:20210331-386 --arch 386

    - name: push latest manifest
      run: |
        docker manifest push ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest  