name: Docker image build and push

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build latest Image
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # AMD64 nativ
          - { wscan-version: 20231015, arch: amd64, locale: en_US, libversion: 1.8.0, pluginversion: 2024.09.15, runner: ubuntu-24.04, platform: linux/amd64 }
          - { wscan-version: 20231015, arch: amd64, locale: de_DE, libversion: 1.8.0, pluginversion: 2024.09.15, runner: ubuntu-24.04, platform: linux/amd64 }
          
          # ARM64 nativ
          - { wscan-version: 20231015, arch: arm64, locale: en_US, libversion: 1.8.0, pluginversion: 2024.09.15, runner: ubuntu-24.04-arm, platform: linux/arm64 }
          - { wscan-version: 20231015, arch: arm64, locale: de_DE, libversion: 1.8.0, pluginversion: 2024.09.15, runner: ubuntu-24.04-arm, platform: linux/arm64 }
          
          # QEMU builds
          - { wscan-version: 20231015, arch: 386, locale: en_US, libversion: 1.8.0, pluginversion: 2024.09.15, runner: ubuntu-24.04, platform: linux/386, qemu: true }
          - { wscan-version: 20231015, arch: 386, locale: de_DE, libversion: 1.8.0, pluginversion: 2024.09.15, runner: ubuntu-24.04, platform: linux/386, qemu: true }
          - { wscan-version: 20231015, arch: arm, locale: en_US, variant: v6, libversion: 1.8.0, pluginversion: 2024.09.15, runner: ubuntu-24.04, platform: linux/arm/v6, qemu: true }
          - { wscan-version: 20231015, arch: arm, locale: en_US, variant: v7, libversion: 1.8.0, pluginversion: 2024.09.15, runner: ubuntu-24.04, platform: linux/arm/v7, qemu: true }
          - { wscan-version: 20231015, arch: arm, locale: de_DE, variant: v6, libversion: 1.8.0, pluginversion: 2024.09.15, runner: ubuntu-24.04, platform: linux/arm/v6, qemu: true }
          - { wscan-version: 20231015, arch: arm, locale: de_DE, variant: v7, libversion: 1.8.0, pluginversion: 2024.09.15, runner: ubuntu-24.04, platform: linux/arm/v7, qemu: true }
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      if: matrix.qemu == true
      uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ matrix.platform }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Build latest image
      id: build-image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: ${{ matrix.platform }}
        tags: ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-${{ matrix.arch }}${{ matrix.variant }}
        build-args: |
          VERSION=${{ matrix.wscan-version }}
          LOCALE=${{ matrix.locale }}.UTF-8
          LIBVERSION=${{ matrix.libversion }}
          PLUGINVERSION=${{ matrix.pluginversion }}
        push: true
        cache-from: type=gha,scope=${{ matrix.arch }}${{ matrix.variant }}
        cache-to: type=gha,mode=max,scope=${{ matrix.arch }}${{ matrix.variant }}

  create-manifest:
    needs: build
    name: Create and push manifest for multiarch image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        wscan-version: [20231015]
        locale: [en_US, de_DE]

    steps:
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: create version manifest list
      run: |
        docker manifest create ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }} \
          --amend ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-arm64 \
          --amend ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-amd64 \
          --amend ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-386 \
          --amend ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-armv6 \
          --amend ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-armv7
        
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }} \
          ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-arm64 --arch arm64
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }} \
          ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-amd64 --arch amd64
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }} \
          ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-386 --arch 386
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }} \
          ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-armv6 --arch arm --variant v6
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }} \
          ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-armv7 --arch arm --variant v7

    - name: push version manifest
      run: |
        docker manifest push ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}

    - name: create latest-locale manifest list
      run: |
        docker manifest create ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest-${{ matrix.locale }} \
          --amend ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-arm64 \
          --amend ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-amd64 \
          --amend ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-386 \
          --amend ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-armv6 \
          --amend ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-armv7
        
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest-${{ matrix.locale }} \
          ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-arm64 --arch arm64
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest-${{ matrix.locale }} \
          ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-amd64 --arch amd64
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest-${{ matrix.locale }} \
          ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-386 --arch 386
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest-${{ matrix.locale }} \
          ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-armv6 --arch arm --variant v6
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest-${{ matrix.locale }} \
          ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-armv7 --arch arm --variant v7
    
    - name: push latest manifest
      run: |
        docker manifest push ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest-${{ matrix.locale }}

    - name: create latest manifest list
      if: ${{ matrix.locale == 'en_US' }}
      run: |
        docker manifest create ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest \
          --amend ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-arm64 \
          --amend ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-amd64 \
          --amend ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-386 \
          --amend ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-armv6 \
          --amend ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-armv7
        
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest \
          ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-arm64 --arch arm64
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest \
          ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-amd64 --arch amd64
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest \
          ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-386 --arch 386
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest \
          ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-armv6 --arch arm --variant v6
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest \
          ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-armv7 --arch arm --variant v7

    - name: push latest manifest
      if: ${{ matrix.locale == 'en_US' }}
      run: |
        docker manifest push ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest
