name: Docker image build

on:
  push:

jobs:
  build:
    name: Build latest Image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64, 386]

    steps:
    - uses: actions/checkout@v2

    - name: Prepare multiarch
      run: sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes
          
    - name: Build latest image
      id: build-latest-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: w_scan_cpp
        archs: ${{ matrix.arch }}
        tags: latest-${{ matrix.arch }}
        dockerfiles: |
          ./Dockerfile
        build-args: |
          VERSION=20210331
