name: Docker image build and test

on: 
  pull_request:
    branches:
      - 'main'
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    name: Build latest Image
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        wscan-version: [20231015]
        arch: [386, amd64, arm64]
        locale: [en_US, de_DE]
        libversion: [1.8.0]
        pluginversion: [2024.09.15]
        include:
          - { wscan-version: 20231015, pluginversion: 2024.09.15, libversion: 1.8.0, arch: arm, locale: en_US, variant: v6 }
          - { wscan-version: 20231015, pluginversion: 2024.09.15, libversion: 1.8.0, arch: arm, locale: en_US, variant: v7 }
          - { wscan-version: 20231015, pluginversion: 2024.09.15, libversion: 1.8.0, arch: arm, locale: de_DE, variant: v6 }
          - { wscan-version: 20231015, pluginversion: 2024.09.15, libversion: 1.8.0, arch: arm, locale: de_DE, variant: v7 }
    steps:
    - uses: actions/checkout@v4

    - name: Prepare multiarch
      run: sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes
          
    - name: Build latest image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: w_scan_cpp
        archs: ${{ matrix.arch }}
        tags: ${{ matrix.wscan-version }}-${{ matrix.locale }}-${{ matrix.arch }}${{ matrix.variant }}
        dockerfiles: |
          ./Dockerfile
        build-args: |
          VERSION=${{ matrix.wscan-version }}
          LOCALE=${{ matrix.locale }}.UTF-8
          LIBVERSION=${{ matrix.libversion }}
          PLUGINVERSION=${{ matrix.pluginversion }}
        extra-args: |
          --variant=${{ matrix.variant }}
