name: Docker image build and test

on: 
  pull_request:
    branches:
      - master
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    name: Build latest Image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { arch: arm, variant: v6 }
          - { arch: arm, variant: v7 }
          - { arch: amd64, variant: '' }
          - { arch: 386, variant: '' }
          - { arch: arm64, variant: '' }
    steps:
    - uses: actions/checkout@v2

    - name: Prepare multiarch
      run: sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes
          
    - name: Build latest image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: w_scan_cpp
        archs: ${{ matrix.arch }}
        tags: 20210331-${{ matrix.arch }}${{ matrix.variant }}
        dockerfiles: |
          ./Dockerfile
        build-args: |
          VERSION=20210331
        extra-args: |
          --variant=${{ matrix.variant }}
