name: Docker image build and test

on: 
  pull_request:
    branches:
      - master
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    name: Build latest Image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [386, amd64, arm64]
        locale: [en_US.UTF-8, de_DE.UTF-8]
        include:
          - { arch: arm, locale: en_US.UTF-8, variant: v6 }
          - { arch: arm, locale: en_US.UTF-8, variant: v7 }
          - { arch: arm, locale: de_DE.UTF-8, variant: v6 }
          - { arch: arm, locale: de_DE.UTF-8, variant: v7 }
    steps:
    - uses: actions/checkout@v2

    - name: Prepare multiarch
      run: sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes
          
    - name: Build latest image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: w_scan_cpp
        archs: ${{ matrix.arch }}
        tags: 20210331-${{ matrix.locale }}-${{ matrix.arch }}${{ matrix.variant }}
        dockerfiles: |
          ./Dockerfile
        build-args: |
          VERSION=20210331
          LOCALE=${{ matrix.locale }}
        extra-args: |
          --variant=${{ matrix.variant }}
