name: Docker image build and push

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build latest Image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        wscan-version: [20230604]
        arch: [386, amd64, arm64]
        locale: [en_US, de_DE]
        libversion: [1.7.0]
        include:
          - { wscan-version: 20230604, libversion: 1.7.0, arch: arm, locale: en_US, variant: v6 }
          - { wscan-version: 20230604, libversion: 1.7.0, arch: arm, locale: en_US, variant: v7 }
          - { wscan-version: 20230604, libversion: 1.7.0, arch: arm, locale: de_DE, variant: v6 }
          - { wscan-version: 20230604, libversion: 1.7.0, arch: arm, locale: de_DE, variant: v7 }
    steps:
    - uses: actions/checkout@v3

    - name: Prepare multiarch
      run: sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes
          
    - name: Build latest image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: w_scan_cpp
        archs: ${{ matrix.arch }}
        tags: ${{ matrix.wscan-version }}-${{ matrix.locale }}-${{ matrix.arch }}${{ matrix.variant }}
        dockerfiles: |
          ./Dockerfile
        build-args: |
          VERSION=${{ matrix.wscan-version }}
          LOCALE=${{ matrix.locale }}.UTF-8
          LIBVERSION=${{ matrix.libversion }}
        extra-args: |
          --variant=${{ matrix.variant }}


    - name: Push latest image to ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ghcr.io/${{ github.repository_owner }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
  
  create-manifest:
    needs: build
    name: Create and push manifest for multiarch image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        wscan-version: [20230604]
        locale: [en_US, de_DE]

    steps:
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: pull latest images
      run: |
        docker pull ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-arm64 
        docker pull ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-amd64
        docker pull ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-386
        docker pull ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-armv6
        docker pull ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-armv7

    - name: create version manifest list
      run: |
        docker manifest create ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }} ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-arm64 ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-amd64 ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-386 ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-armv6 ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-armv7
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }} ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-arm64 --arch arm64
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }} ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-amd64 --arch amd64
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }} ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-386 --arch 386
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }} ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-armv6 --arch arm --variant v6
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }} ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-armv7 --arch arm --variant v7

    - name: push version manifest
      run: |
        docker manifest push ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}

    - name: create latest-locale manifest list
      run: |
        docker manifest create ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest-${{ matrix.locale }} ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-arm64 ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-amd64 ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-386  ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-armv6 ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-armv7
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest-${{ matrix.locale }} ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-arm64 --arch arm64
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest-${{ matrix.locale }} ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-amd64 --arch amd64
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest-${{ matrix.locale }} ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-386 --arch 386
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest-${{ matrix.locale }} ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-armv6 --arch arm --variant v6
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest-${{ matrix.locale }} ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-armv7 --arch arm --variant v7
    
    - name: push latest manifest
      run: |
        docker manifest push ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest-${{ matrix.locale }}

    - name: create latest manifest list
      if: ${{ matrix.locale == 'en_US' }}
      run: |
        docker manifest create ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-arm64 ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-amd64 ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-386  ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-armv6 ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-armv7
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-arm64 --arch arm64
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-amd64 --arch amd64
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-386 --arch 386
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-armv6 --arch arm --variant v6
        docker manifest annotate ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest ghcr.io/${{ github.repository_owner }}/w_scan_cpp:${{ matrix.wscan-version }}-${{ matrix.locale }}-armv7 --arch arm --variant v7

    - name: push latest manifest
      if: ${{ matrix.locale == 'en_US' }}
      run: |
        docker manifest push ghcr.io/${{ github.repository_owner }}/w_scan_cpp:latest
